name: "Prod Deploy"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
    call-terraform:
      uses: ./.github/workflows/terraform.yml
      with:
        environment: "prod"
        aws-assume-role-arn: arn:aws:iam::829115578807:role/github-actions-igorrodriguesss
        aws-region: "us-east-1"
        aws-statefile-s3-bucket: igorrodriguesss-us-east-1-terraform-statefile
        aws-lock-dynamodb-table: igorrodriguesss-us-east-1-terraform-lock
